language: scala
scala:
  - 2.10.4
  - 2.11.0

script: sbt ++$TRAVIS_SCALA_VERSION test -Dloglevel=debug

before_install: gem install fluentd

jdk:
 - openjdk7
 - oraclejdk7

branches:
  only:
    - master
    - develop

notifications:
  email:
    - leo@xerial.org
    - ozawa.tsuyoshi@gmail.com
