language: scala
scala:
  - 2.11.8
  - 2.12.1

sudo: false

script: sbt ++$TRAVIS_SCALA_VERSION test

before_install:
  - rvm install 2.2.0
  - rvm use 2.2.0
  - gem install fluentd -v 0.14.11

jdk:
 - oraclejdk8
